using Microsoft.EntityFrameworkCore.Migrations;
using System;

#nullable disable

namespace Persistence.Migrations
{
    /// <inheritdoc />
    public partial class _init : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "UserOperationClaims",
                keyColumn: "Id",
                keyValue: new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
            );

            migrationBuilder.DeleteData(
                table: "OperationClaims",
                keyColumn: "Id",
                keyValue: new Guid("00000000-0000-0000-0000-000000000003")
            );

            migrationBuilder.DropColumn(name: "ImagePath", table: "UserImages");

            migrationBuilder.DropColumn(name: "StorageType", table: "UserImages");

            migrationBuilder.AlterColumn<string>(
                name: "UserName",
                table: "Users",
                type: "character varying(50)",
                maxLength: 50,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text"
            );

            migrationBuilder.AlterColumn<string>(
                name: "Surname",
                table: "Users",
                type: "character varying(50)",
                maxLength: 50,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text"
            );

            migrationBuilder.AlterColumn<string>(
                name: "PhoneNumber",
                table: "Users",
                type: "character varying(15)",
                maxLength: 15,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text"
            );

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Users",
                type: "character varying(50)",
                maxLength: 50,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text"
            );

            migrationBuilder.AlterColumn<string>(
                name: "Email",
                table: "Users",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text"
            );

            migrationBuilder.AlterColumn<string>(
                name: "CountryCode",
                table: "Users",
                type: "character varying(5)",
                maxLength: 5,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text"
            );

            migrationBuilder.AddColumn<int>(
                name: "TotalSearchCount",
                table: "Users",
                type: "integer",
                nullable: false,
                defaultValue: 0
            );

            migrationBuilder.AlterColumn<string>(
                name: "Tags",
                table: "UserImages",
                type: "character varying(500)",
                maxLength: 500,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true
            );

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                table: "UserImages",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text"
            );

            migrationBuilder.AddColumn<int>(
                name: "DescriptionType",
                table: "UserImages",
                type: "integer",
                nullable: false,
                defaultValue: 0
            );

            migrationBuilder.AddColumn<Guid>(
                name: "FileAttachmentId",
                table: "UserImages",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000")
            );

            migrationBuilder.CreateTable(
                name: "FileAttachments",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    FileName = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    FilePath = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    StorageType = table.Column<int>(type: "integer", nullable: false),
                    UploadDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UserImageId = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FileAttachments", x => x.Id);
                }
            );

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("11111111-1111-1111-1111-111111111111"),
                columns: new[] { "PasswordHash", "PasswordSalt", "TotalSearchCount" },
                values: new object[]
                {
                    new byte[]
                    {
                        211,
                        27,
                        64,
                        116,
                        243,
                        181,
                        79,
                        178,
                        93,
                        143,
                        56,
                        84,
                        65,
                        151,
                        179,
                        61,
                        152,
                        21,
                        73,
                        57,
                        209,
                        184,
                        198,
                        61,
                        222,
                        103,
                        123,
                        49,
                        139,
                        153,
                        64,
                        137,
                        184,
                        83,
                        150,
                        207,
                        113,
                        107,
                        16,
                        170,
                        89,
                        253,
                        88,
                        16,
                        119,
                        76,
                        88,
                        57,
                        130,
                        84,
                        61,
                        33,
                        227,
                        0,
                        30,
                        160,
                        163,
                        148,
                        141,
                        29,
                        100,
                        209,
                        179,
                        225
                    },
                    new byte[]
                    {
                        212,
                        49,
                        7,
                        145,
                        47,
                        195,
                        238,
                        140,
                        101,
                        255,
                        6,
                        233,
                        231,
                        254,
                        134,
                        26,
                        101,
                        190,
                        65,
                        113,
                        181,
                        199,
                        43,
                        162,
                        186,
                        71,
                        214,
                        90,
                        166,
                        106,
                        3,
                        149,
                        87,
                        158,
                        167,
                        211,
                        149,
                        77,
                        27,
                        126,
                        22,
                        73,
                        53,
                        22,
                        36,
                        16,
                        198,
                        243,
                        140,
                        100,
                        227,
                        8,
                        26,
                        123,
                        154,
                        237,
                        0,
                        116,
                        130,
                        87,
                        18,
                        254,
                        36,
                        235,
                        55,
                        73,
                        210,
                        107,
                        165,
                        152,
                        69,
                        58,
                        2,
                        203,
                        242,
                        96,
                        134,
                        254,
                        53,
                        7,
                        171,
                        151,
                        240,
                        66,
                        122,
                        112,
                        129,
                        118,
                        207,
                        16,
                        239,
                        26,
                        191,
                        70,
                        33,
                        106,
                        117,
                        78,
                        109,
                        199,
                        245,
                        193,
                        73,
                        87,
                        207,
                        60,
                        151,
                        213,
                        85,
                        156,
                        210,
                        204,
                        24,
                        105,
                        129,
                        161,
                        150,
                        106,
                        23,
                        181,
                        68,
                        54,
                        133,
                        116,
                        39,
                        160,
                        142,
                        32
                    },
                    0
                }
            );

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("22222222-2222-2222-2222-222222222222"),
                columns: new[] { "PasswordHash", "PasswordSalt", "TotalSearchCount" },
                values: new object[]
                {
                    new byte[]
                    {
                        154,
                        3,
                        50,
                        192,
                        180,
                        109,
                        197,
                        114,
                        231,
                        48,
                        7,
                        61,
                        221,
                        53,
                        12,
                        26,
                        239,
                        187,
                        196,
                        6,
                        168,
                        188,
                        238,
                        17,
                        8,
                        15,
                        73,
                        81,
                        244,
                        163,
                        255,
                        16,
                        225,
                        70,
                        179,
                        184,
                        41,
                        177,
                        124,
                        166,
                        253,
                        168,
                        60,
                        182,
                        167,
                        216,
                        26,
                        203,
                        95,
                        100,
                        191,
                        36,
                        54,
                        163,
                        134,
                        197,
                        36,
                        213,
                        81,
                        76,
                        170,
                        227,
                        192,
                        219
                    },
                    new byte[]
                    {
                        13,
                        165,
                        69,
                        249,
                        184,
                        113,
                        155,
                        108,
                        63,
                        220,
                        11,
                        68,
                        94,
                        145,
                        56,
                        172,
                        97,
                        252,
                        221,
                        228,
                        204,
                        97,
                        174,
                        168,
                        125,
                        208,
                        155,
                        197,
                        148,
                        50,
                        201,
                        30,
                        29,
                        150,
                        75,
                        133,
                        95,
                        19,
                        220,
                        209,
                        12,
                        107,
                        230,
                        2,
                        189,
                        43,
                        39,
                        27,
                        10,
                        123,
                        94,
                        194,
                        98,
                        67,
                        150,
                        5,
                        251,
                        90,
                        175,
                        134,
                        122,
                        114,
                        185,
                        47,
                        110,
                        36,
                        196,
                        177,
                        73,
                        80,
                        133,
                        204,
                        78,
                        131,
                        235,
                        161,
                        244,
                        144,
                        230,
                        6,
                        50,
                        74,
                        208,
                        250,
                        74,
                        195,
                        84,
                        150,
                        242,
                        217,
                        173,
                        77,
                        82,
                        90,
                        201,
                        104,
                        250,
                        64,
                        138,
                        83,
                        156,
                        216,
                        222,
                        43,
                        47,
                        154,
                        143,
                        204,
                        217,
                        231,
                        4,
                        78,
                        124,
                        29,
                        228,
                        198,
                        169,
                        162,
                        232,
                        92,
                        6,
                        176,
                        176,
                        52,
                        181,
                        200,
                        197,
                        196
                    },
                    0
                }
            );

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("33333333-3333-3333-3333-333333333333"),
                columns: new[] { "PasswordHash", "PasswordSalt", "TotalSearchCount" },
                values: new object[]
                {
                    new byte[]
                    {
                        250,
                        15,
                        224,
                        67,
                        150,
                        92,
                        67,
                        216,
                        69,
                        218,
                        50,
                        243,
                        228,
                        234,
                        45,
                        196,
                        126,
                        191,
                        47,
                        65,
                        52,
                        210,
                        86,
                        2,
                        202,
                        143,
                        226,
                        2,
                        174,
                        217,
                        49,
                        118,
                        4,
                        210,
                        9,
                        20,
                        68,
                        250,
                        23,
                        20,
                        100,
                        207,
                        248,
                        134,
                        124,
                        165,
                        177,
                        16,
                        171,
                        165,
                        239,
                        20,
                        197,
                        1,
                        149,
                        85,
                        208,
                        125,
                        148,
                        63,
                        51,
                        47,
                        215,
                        206
                    },
                    new byte[]
                    {
                        138,
                        185,
                        215,
                        186,
                        217,
                        41,
                        180,
                        129,
                        99,
                        127,
                        141,
                        41,
                        39,
                        243,
                        212,
                        6,
                        235,
                        130,
                        82,
                        125,
                        220,
                        189,
                        169,
                        31,
                        113,
                        131,
                        147,
                        17,
                        49,
                        112,
                        154,
                        86,
                        155,
                        25,
                        208,
                        171,
                        50,
                        30,
                        184,
                        89,
                        205,
                        165,
                        228,
                        186,
                        26,
                        10,
                        159,
                        191,
                        30,
                        152,
                        123,
                        83,
                        107,
                        68,
                        149,
                        45,
                        186,
                        168,
                        30,
                        228,
                        242,
                        151,
                        174,
                        154,
                        58,
                        37,
                        243,
                        184,
                        25,
                        234,
                        25,
                        149,
                        70,
                        126,
                        123,
                        245,
                        58,
                        214,
                        139,
                        159,
                        104,
                        203,
                        16,
                        51,
                        204,
                        89,
                        242,
                        100,
                        248,
                        58,
                        43,
                        25,
                        185,
                        31,
                        52,
                        229,
                        29,
                        169,
                        231,
                        142,
                        47,
                        150,
                        165,
                        39,
                        206,
                        106,
                        10,
                        198,
                        97,
                        177,
                        173,
                        205,
                        158,
                        3,
                        49,
                        153,
                        148,
                        129,
                        24,
                        184,
                        249,
                        82,
                        166,
                        209,
                        142,
                        179,
                        222,
                        71
                    },
                    0
                }
            );

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("44444444-4444-4444-4444-444444444444"),
                columns: new[] { "PasswordHash", "PasswordSalt", "TotalSearchCount" },
                values: new object[]
                {
                    new byte[]
                    {
                        48,
                        178,
                        212,
                        39,
                        221,
                        11,
                        67,
                        52,
                        2,
                        93,
                        104,
                        49,
                        147,
                        91,
                        143,
                        202,
                        201,
                        172,
                        104,
                        122,
                        202,
                        231,
                        169,
                        246,
                        238,
                        151,
                        174,
                        0,
                        2,
                        88,
                        45,
                        108,
                        68,
                        149,
                        3,
                        71,
                        247,
                        73,
                        85,
                        231,
                        15,
                        10,
                        36,
                        70,
                        50,
                        191,
                        242,
                        30,
                        71,
                        209,
                        38,
                        226,
                        56,
                        28,
                        178,
                        172,
                        109,
                        182,
                        181,
                        154,
                        236,
                        41,
                        156,
                        39
                    },
                    new byte[]
                    {
                        82,
                        153,
                        125,
                        76,
                        229,
                        80,
                        96,
                        213,
                        58,
                        220,
                        6,
                        192,
                        120,
                        219,
                        177,
                        141,
                        205,
                        76,
                        29,
                        213,
                        48,
                        165,
                        30,
                        125,
                        92,
                        213,
                        209,
                        74,
                        110,
                        131,
                        231,
                        59,
                        205,
                        35,
                        229,
                        94,
                        7,
                        33,
                        155,
                        239,
                        248,
                        209,
                        221,
                        192,
                        210,
                        112,
                        160,
                        253,
                        156,
                        92,
                        127,
                        202,
                        253,
                        123,
                        8,
                        86,
                        88,
                        123,
                        255,
                        91,
                        161,
                        56,
                        75,
                        68,
                        231,
                        179,
                        109,
                        140,
                        223,
                        207,
                        165,
                        18,
                        84,
                        77,
                        177,
                        217,
                        223,
                        170,
                        143,
                        128,
                        48,
                        163,
                        184,
                        187,
                        107,
                        131,
                        239,
                        184,
                        218,
                        211,
                        21,
                        197,
                        86,
                        159,
                        236,
                        137,
                        79,
                        6,
                        204,
                        251,
                        141,
                        51,
                        109,
                        146,
                        55,
                        122,
                        101,
                        22,
                        37,
                        66,
                        201,
                        66,
                        23,
                        135,
                        95,
                        131,
                        195,
                        20,
                        12,
                        158,
                        18,
                        98,
                        151,
                        204,
                        2,
                        189,
                        56,
                        35
                    },
                    0
                }
            );

            migrationBuilder.CreateIndex(
                name: "IX_Users_CountryCode_PhoneNumber",
                table: "Users",
                columns: new[] { "CountryCode", "PhoneNumber" },
                unique: true
            );

            migrationBuilder.CreateIndex(name: "IX_Users_Email", table: "Users", column: "Email", unique: true);

            migrationBuilder.CreateIndex(name: "IX_Users_UserName", table: "Users", column: "UserName", unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_UserImages_FileAttachmentId",
                table: "UserImages",
                column: "FileAttachmentId",
                unique: true
            );

            migrationBuilder.AddForeignKey(
                name: "FK_UserImages_FileAttachments_FileAttachmentId",
                table: "UserImages",
                column: "FileAttachmentId",
                principalTable: "FileAttachments",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict
            );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(name: "FK_UserImages_FileAttachments_FileAttachmentId", table: "UserImages");

            migrationBuilder.DropTable(name: "FileAttachments");

            migrationBuilder.DropIndex(name: "IX_Users_CountryCode_PhoneNumber", table: "Users");

            migrationBuilder.DropIndex(name: "IX_Users_Email", table: "Users");

            migrationBuilder.DropIndex(name: "IX_Users_UserName", table: "Users");

            migrationBuilder.DropIndex(name: "IX_UserImages_FileAttachmentId", table: "UserImages");

            migrationBuilder.DropColumn(name: "TotalSearchCount", table: "Users");

            migrationBuilder.DropColumn(name: "DescriptionType", table: "UserImages");

            migrationBuilder.DropColumn(name: "FileAttachmentId", table: "UserImages");

            migrationBuilder.AlterColumn<string>(
                name: "UserName",
                table: "Users",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(50)",
                oldMaxLength: 50
            );

            migrationBuilder.AlterColumn<string>(
                name: "Surname",
                table: "Users",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(50)",
                oldMaxLength: 50
            );

            migrationBuilder.AlterColumn<string>(
                name: "PhoneNumber",
                table: "Users",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(15)",
                oldMaxLength: 15
            );

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Users",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(50)",
                oldMaxLength: 50
            );

            migrationBuilder.AlterColumn<string>(
                name: "Email",
                table: "Users",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(100)",
                oldMaxLength: 100
            );

            migrationBuilder.AlterColumn<string>(
                name: "CountryCode",
                table: "Users",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(5)",
                oldMaxLength: 5
            );

            migrationBuilder.AlterColumn<string>(
                name: "Tags",
                table: "UserImages",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(500)",
                oldMaxLength: 500,
                oldNullable: true
            );

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                table: "UserImages",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(500)",
                oldMaxLength: 500
            );

            migrationBuilder.AddColumn<string>(
                name: "ImagePath",
                table: "UserImages",
                type: "text",
                nullable: false,
                defaultValue: ""
            );

            migrationBuilder.AddColumn<string>(
                name: "StorageType",
                table: "UserImages",
                type: "text",
                nullable: false,
                defaultValue: ""
            );

            migrationBuilder.InsertData(
                table: "OperationClaims",
                columns: new[] { "Id", "CreatedDate", "DeletedDate", "Name", "UpdatedDate" },
                values: new object[]
                {
                    new Guid("00000000-0000-0000-0000-000000000003"),
                    new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    null,
                    "DemoUser",
                    null
                }
            );

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("11111111-1111-1111-1111-111111111111"),
                columns: new[] { "PasswordHash", "PasswordSalt" },
                values: new object[]
                {
                    new byte[]
                    {
                        109,
                        160,
                        105,
                        75,
                        241,
                        116,
                        48,
                        18,
                        233,
                        185,
                        249,
                        20,
                        96,
                        70,
                        236,
                        247,
                        208,
                        176,
                        214,
                        70,
                        165,
                        130,
                        68,
                        82,
                        178,
                        104,
                        207,
                        42,
                        48,
                        150,
                        65,
                        220,
                        73,
                        152,
                        155,
                        225,
                        128,
                        78,
                        105,
                        212,
                        85,
                        152,
                        238,
                        135,
                        93,
                        189,
                        120,
                        114,
                        241,
                        89,
                        145,
                        13,
                        241,
                        111,
                        173,
                        175,
                        134,
                        243,
                        94,
                        216,
                        19,
                        127,
                        219,
                        93
                    },
                    new byte[]
                    {
                        119,
                        169,
                        78,
                        1,
                        82,
                        254,
                        132,
                        192,
                        75,
                        233,
                        194,
                        135,
                        43,
                        102,
                        138,
                        116,
                        90,
                        44,
                        165,
                        218,
                        33,
                        225,
                        217,
                        133,
                        164,
                        145,
                        224,
                        175,
                        85,
                        185,
                        78,
                        105,
                        125,
                        246,
                        122,
                        89,
                        50,
                        135,
                        27,
                        8,
                        226,
                        89,
                        92,
                        188,
                        153,
                        138,
                        247,
                        102,
                        49,
                        97,
                        51,
                        32,
                        237,
                        241,
                        228,
                        235,
                        19,
                        17,
                        74,
                        105,
                        137,
                        78,
                        6,
                        133,
                        179,
                        10,
                        109,
                        41,
                        244,
                        75,
                        32,
                        129,
                        192,
                        55,
                        151,
                        120,
                        251,
                        21,
                        98,
                        107,
                        98,
                        125,
                        132,
                        19,
                        241,
                        9,
                        151,
                        140,
                        159,
                        125,
                        28,
                        26,
                        113,
                        238,
                        6,
                        61,
                        78,
                        146,
                        181,
                        155,
                        49,
                        151,
                        85,
                        23,
                        94,
                        204,
                        35,
                        221,
                        254,
                        140,
                        2,
                        76,
                        192,
                        84,
                        209,
                        177,
                        234,
                        58,
                        127,
                        222,
                        229,
                        222,
                        68,
                        55,
                        122,
                        68,
                        225,
                        81
                    }
                }
            );

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("22222222-2222-2222-2222-222222222222"),
                columns: new[] { "PasswordHash", "PasswordSalt" },
                values: new object[]
                {
                    new byte[]
                    {
                        42,
                        138,
                        9,
                        188,
                        241,
                        12,
                        113,
                        223,
                        149,
                        218,
                        231,
                        89,
                        116,
                        26,
                        26,
                        169,
                        197,
                        161,
                        246,
                        41,
                        166,
                        57,
                        198,
                        78,
                        246,
                        72,
                        214,
                        152,
                        75,
                        225,
                        35,
                        236,
                        35,
                        46,
                        13,
                        222,
                        193,
                        80,
                        72,
                        214,
                        94,
                        157,
                        191,
                        64,
                        168,
                        80,
                        177,
                        129,
                        158,
                        176,
                        3,
                        208,
                        16,
                        173,
                        70,
                        197,
                        225,
                        127,
                        32,
                        90,
                        104,
                        103,
                        45,
                        7
                    },
                    new byte[]
                    {
                        165,
                        95,
                        245,
                        157,
                        68,
                        226,
                        38,
                        70,
                        186,
                        33,
                        92,
                        16,
                        110,
                        30,
                        218,
                        237,
                        213,
                        61,
                        254,
                        40,
                        229,
                        254,
                        218,
                        46,
                        97,
                        26,
                        113,
                        209,
                        188,
                        17,
                        0,
                        181,
                        152,
                        249,
                        76,
                        169,
                        123,
                        208,
                        121,
                        79,
                        30,
                        144,
                        174,
                        20,
                        137,
                        61,
                        232,
                        38,
                        109,
                        50,
                        68,
                        131,
                        177,
                        27,
                        117,
                        199,
                        7,
                        179,
                        197,
                        104,
                        228,
                        248,
                        57,
                        222,
                        212,
                        216,
                        188,
                        193,
                        212,
                        47,
                        102,
                        55,
                        24,
                        28,
                        133,
                        210,
                        187,
                        129,
                        33,
                        67,
                        225,
                        226,
                        157,
                        226,
                        226,
                        245,
                        200,
                        15,
                        153,
                        44,
                        77,
                        10,
                        36,
                        78,
                        74,
                        26,
                        26,
                        198,
                        160,
                        243,
                        59,
                        77,
                        187,
                        196,
                        164,
                        121,
                        6,
                        250,
                        251,
                        129,
                        196,
                        82,
                        174,
                        229,
                        155,
                        247,
                        154,
                        53,
                        159,
                        36,
                        249,
                        133,
                        67,
                        189,
                        216,
                        68,
                        213,
                        178
                    }
                }
            );

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("33333333-3333-3333-3333-333333333333"),
                columns: new[] { "PasswordHash", "PasswordSalt" },
                values: new object[]
                {
                    new byte[]
                    {
                        254,
                        75,
                        129,
                        99,
                        189,
                        121,
                        139,
                        155,
                        125,
                        232,
                        214,
                        212,
                        215,
                        185,
                        239,
                        84,
                        11,
                        0,
                        145,
                        76,
                        128,
                        111,
                        65,
                        92,
                        157,
                        193,
                        148,
                        193,
                        192,
                        179,
                        185,
                        71,
                        199,
                        66,
                        179,
                        119,
                        45,
                        59,
                        131,
                        107,
                        179,
                        135,
                        161,
                        207,
                        74,
                        185,
                        35,
                        101,
                        109,
                        202,
                        236,
                        39,
                        105,
                        225,
                        200,
                        252,
                        129,
                        99,
                        140,
                        18,
                        188,
                        203,
                        229,
                        185
                    },
                    new byte[]
                    {
                        40,
                        18,
                        83,
                        177,
                        208,
                        175,
                        67,
                        185,
                        100,
                        99,
                        70,
                        216,
                        190,
                        91,
                        85,
                        20,
                        167,
                        164,
                        239,
                        84,
                        53,
                        132,
                        147,
                        39,
                        240,
                        88,
                        108,
                        136,
                        179,
                        70,
                        196,
                        27,
                        29,
                        251,
                        171,
                        165,
                        45,
                        186,
                        182,
                        78,
                        227,
                        34,
                        55,
                        149,
                        115,
                        234,
                        168,
                        109,
                        46,
                        116,
                        249,
                        177,
                        112,
                        130,
                        215,
                        17,
                        24,
                        178,
                        65,
                        74,
                        36,
                        102,
                        189,
                        254,
                        99,
                        186,
                        246,
                        43,
                        115,
                        255,
                        217,
                        88,
                        78,
                        171,
                        102,
                        124,
                        162,
                        215,
                        51,
                        119,
                        152,
                        250,
                        100,
                        241,
                        58,
                        156,
                        6,
                        118,
                        78,
                        200,
                        2,
                        86,
                        225,
                        231,
                        46,
                        197,
                        64,
                        222,
                        61,
                        184,
                        159,
                        34,
                        96,
                        180,
                        134,
                        34,
                        229,
                        82,
                        8,
                        173,
                        185,
                        12,
                        80,
                        104,
                        221,
                        73,
                        117,
                        203,
                        221,
                        102,
                        19,
                        118,
                        197,
                        222,
                        30,
                        192,
                        15,
                        186
                    }
                }
            );

            migrationBuilder.UpdateData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("44444444-4444-4444-4444-444444444444"),
                columns: new[] { "PasswordHash", "PasswordSalt" },
                values: new object[]
                {
                    new byte[]
                    {
                        12,
                        231,
                        133,
                        31,
                        220,
                        48,
                        138,
                        98,
                        2,
                        110,
                        31,
                        93,
                        58,
                        77,
                        114,
                        139,
                        58,
                        74,
                        129,
                        93,
                        9,
                        250,
                        96,
                        52,
                        136,
                        102,
                        135,
                        245,
                        109,
                        221,
                        170,
                        5,
                        223,
                        23,
                        128,
                        184,
                        185,
                        178,
                        168,
                        160,
                        43,
                        40,
                        255,
                        102,
                        119,
                        94,
                        151,
                        111,
                        167,
                        81,
                        176,
                        19,
                        10,
                        138,
                        236,
                        2,
                        154,
                        135,
                        107,
                        174,
                        149,
                        97,
                        120,
                        107
                    },
                    new byte[]
                    {
                        47,
                        28,
                        204,
                        238,
                        83,
                        176,
                        21,
                        156,
                        205,
                        239,
                        79,
                        147,
                        139,
                        41,
                        177,
                        65,
                        53,
                        1,
                        88,
                        190,
                        253,
                        186,
                        124,
                        227,
                        86,
                        2,
                        100,
                        241,
                        71,
                        218,
                        179,
                        2,
                        235,
                        25,
                        117,
                        1,
                        164,
                        131,
                        116,
                        94,
                        135,
                        3,
                        57,
                        213,
                        101,
                        201,
                        6,
                        164,
                        182,
                        152,
                        46,
                        61,
                        16,
                        111,
                        123,
                        51,
                        216,
                        248,
                        68,
                        177,
                        250,
                        169,
                        122,
                        236,
                        211,
                        44,
                        45,
                        4,
                        112,
                        44,
                        82,
                        180,
                        53,
                        202,
                        88,
                        247,
                        25,
                        28,
                        140,
                        173,
                        100,
                        177,
                        123,
                        150,
                        244,
                        2,
                        238,
                        17,
                        219,
                        69,
                        100,
                        243,
                        251,
                        236,
                        216,
                        177,
                        150,
                        57,
                        66,
                        177,
                        135,
                        182,
                        221,
                        249,
                        41,
                        196,
                        236,
                        185,
                        226,
                        187,
                        33,
                        247,
                        66,
                        179,
                        118,
                        41,
                        251,
                        0,
                        142,
                        154,
                        10,
                        34,
                        227,
                        180,
                        114,
                        54,
                        3,
                        54
                    }
                }
            );

            migrationBuilder.InsertData(
                table: "UserOperationClaims",
                columns: new[] { "Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId" },
                values: new object[]
                {
                    new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                    new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    null,
                    new Guid("00000000-0000-0000-0000-000000000003"),
                    null,
                    new Guid("33333333-3333-3333-3333-333333333333")
                }
            );
        }
    }
}
